import { defineConfig } from "vite";
import { resolve } from "path";
import builtinModules from "builtin-modules";

export default defineConfig({
	css: {
		modules: {
			scopeBehaviour: "local",
			localsConvention: "camelCase",
		},
	},
	build: {
		lib: {
			entry: resolve(__dirname, "main.ts"),
			formats: ["es"],
			fileName: () => "main.js",
		},
		rollupOptions: {
			external: [
				"obsidian",
				"electron",
				"@codemirror/autocomplete",
				"@codemirror/collab",
				"@codemirror/commands",
				"@codemirror/language",
				"@codemirror/lint",
				"@codemirror/search",
				"@codemirror/state",
				"@codemirror/view",
				"@lezer/common",
				"@lezer/highlight",
				"@lezer/lr",
				...builtinModules, // ✅ Use ESM imported modules
			],
			output: {
				banner: `/*
THIS IS A GENERATED/BUNDLED FILE BY VITE
if you want to view the source, please visit the github repository of this plugin
*/`,
				entryFileNames: "main.js",
				sourcemap: process.env.NODE_ENV !== "production",
				format: "es", // ✅ Ensure format is "es" (ESM)
			},
		},
		outDir: "./dist",
		emptyOutDir: true,
		sourcemap: process.env.NODE_ENV !== "production",
		minify: process.env.NODE_ENV === "production",
	},
	plugins: [],
});
